spring:
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    jackson:
      default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://localhost:3306/bookmarket?createDatabaseIfNotExist=true
    username: root
    password: